-- Sales Mart V1（销售数据集市第一版）物理模型。
--
-- 边界：
-- 1. 只创建 mart_sales，不删除或修改 legacy public Schema（旧 public 模式）。
-- 2. 事实表一行对应一条 Sales Order Line（销售订单明细）。
-- 3. Completed（已完成）事实必须保存完成日期、冻结汇率、人民币销售额和冻结销售成本。
-- 4. Gross Profit / Gross Margin（毛利 / 毛利率）留在下游 Semantic Layer（语义层）派生。

CREATE SCHEMA IF NOT EXISTS mart_sales;

CREATE TABLE IF NOT EXISTS mart_sales.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    year SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    day SMALLINT NOT NULL,
    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date),
    CONSTRAINT ck_dim_date_parts CHECK (
        year = EXTRACT(YEAR FROM full_date)::SMALLINT
        AND quarter = EXTRACT(QUARTER FROM full_date)::SMALLINT
        AND month = EXTRACT(MONTH FROM full_date)::SMALLINT
        AND day = EXTRACT(DAY FROM full_date)::SMALLINT
    ),
    CONSTRAINT ck_dim_date_quarter CHECK (quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_dim_date_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_date_day CHECK (day BETWEEN 1 AND 31),
    CONSTRAINT ck_dim_date_key CHECK (
        date_key = (
            EXTRACT(YEAR FROM full_date)::INTEGER * 10000
            + EXTRACT(MONTH FROM full_date)::INTEGER * 100
            + EXTRACT(DAY FROM full_date)::INTEGER
        )
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_customer (
    customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    customer_name TEXT NOT NULL,
    customer_type TEXT NOT NULL,
    industry TEXT NOT NULL,
    country TEXT NOT NULL,
    customer_region TEXT NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_customer_business_version UNIQUE (customer_id, valid_from),
    CONSTRAINT ck_dim_customer_source_system CHECK (btrim(source_system) <> ''),
    CONSTRAINT ck_dim_customer_version_bounds CHECK (
        valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT ck_dim_customer_current_flag CHECK (
        (is_current AND valid_to IS NULL)
        OR (NOT is_current AND valid_to IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_product (
    product_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    product_name TEXT NOT NULL,
    product_line TEXT NOT NULL,
    product_category TEXT NOT NULL,
    technology_route TEXT NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_product_business_version UNIQUE (product_id, valid_from),
    CONSTRAINT ck_dim_product_source_system CHECK (btrim(source_system) <> ''),
    CONSTRAINT ck_dim_product_version_bounds CHECK (
        valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT ck_dim_product_current_flag CHECK (
        (is_current AND valid_to IS NULL)
        OR (NOT is_current AND valid_to IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_sales_region (
    sales_region_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_region_code VARCHAR(50) NOT NULL,
    sales_region_name TEXT NOT NULL,
    CONSTRAINT uq_dim_sales_region_code UNIQUE (sales_region_code),
    CONSTRAINT ck_dim_sales_region_code CHECK (btrim(sales_region_code) <> '')
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_currency (
    currency_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3) NOT NULL,
    currency_name TEXT NOT NULL,
    is_analysis_currency BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_dim_currency_code UNIQUE (currency_code),
    CONSTRAINT ck_dim_currency_code CHECK (
        char_length(currency_code) = 3
        AND currency_code = btrim(upper(currency_code))
    ),
    CONSTRAINT ck_dim_currency_analysis_code CHECK (
        is_analysis_currency = (currency_code = 'CNY')
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.fct_exchange_rate_daily (
    rate_date_key INTEGER NOT NULL,
    currency_key BIGINT NOT NULL,
    rate_to_cny NUMERIC(20, 8) NOT NULL,
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_fct_exchange_rate_daily PRIMARY KEY (rate_date_key, currency_key),
    CONSTRAINT fk_fct_exchange_rate_date
        FOREIGN KEY (rate_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT fk_fct_exchange_rate_currency
        FOREIGN KEY (currency_key) REFERENCES mart_sales.dim_currency (currency_key),
    CONSTRAINT ck_fct_exchange_rate_positive CHECK (rate_to_cny > 0),
    CONSTRAINT ck_fct_exchange_rate_source_system CHECK (btrim(source_system) <> '')
);

CREATE TABLE IF NOT EXISTS mart_sales.fct_sales_order_line (
    sales_order_line_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(100) NOT NULL,
    order_line_id BIGINT NOT NULL,
    order_line_no INTEGER NOT NULL,
    customer_key BIGINT NOT NULL,
    product_key BIGINT NOT NULL,
    sales_region_key BIGINT NOT NULL,
    transaction_currency_key BIGINT NOT NULL,
    order_date_key INTEGER NOT NULL,
    confirmation_date_key INTEGER,
    completion_date_key INTEGER,
    order_status VARCHAR(20) NOT NULL,
    quantity NUMERIC(20, 6) NOT NULL,
    unit_price_transaction NUMERIC(20, 6) NOT NULL,
    discount_amount_transaction NUMERIC(20, 6) NOT NULL DEFAULT 0,
    gross_sales_amount_transaction NUMERIC(20, 6) NOT NULL,
    net_sales_amount_transaction NUMERIC(20, 6),
    fx_rate_to_cny NUMERIC(20, 8),
    net_sales_amount_cny NUMERIC(20, 6),
    frozen_unit_cost_cny NUMERIC(20, 6),
    sales_cost_amount_cny NUMERIC(20, 6),
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fct_sales_order_line_id UNIQUE (order_line_id),
    CONSTRAINT uq_fct_sales_order_line_order_line_no UNIQUE (order_id, order_line_no),
    CONSTRAINT fk_fct_sales_customer
        FOREIGN KEY (customer_key) REFERENCES mart_sales.dim_customer (customer_key),
    CONSTRAINT fk_fct_sales_product
        FOREIGN KEY (product_key) REFERENCES mart_sales.dim_product (product_key),
    CONSTRAINT fk_fct_sales_region
        FOREIGN KEY (sales_region_key) REFERENCES mart_sales.dim_sales_region (sales_region_key),
    CONSTRAINT fk_fct_sales_currency
        FOREIGN KEY (transaction_currency_key) REFERENCES mart_sales.dim_currency (currency_key),
    CONSTRAINT fk_fct_sales_order_date
        FOREIGN KEY (order_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT fk_fct_sales_confirmation_date
        FOREIGN KEY (confirmation_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT fk_fct_sales_completion_date
        FOREIGN KEY (completion_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT ck_fct_sales_order_line_no CHECK (order_line_no > 0),
    CONSTRAINT ck_fct_sales_order_no CHECK (btrim(order_no) <> ''),
    CONSTRAINT ck_fct_sales_status CHECK (
        order_status IN ('pending', 'confirmed', 'completed', 'cancelled')
    ),
    CONSTRAINT ck_fct_sales_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_fct_sales_unit_price_nonnegative CHECK (unit_price_transaction >= 0),
    CONSTRAINT ck_fct_sales_discount_nonnegative CHECK (discount_amount_transaction >= 0),
    CONSTRAINT ck_fct_sales_gross_nonnegative CHECK (gross_sales_amount_transaction >= 0),
    CONSTRAINT ck_fct_sales_net_transaction_nonnegative CHECK (
        net_sales_amount_transaction IS NULL OR net_sales_amount_transaction >= 0
    ),
    CONSTRAINT ck_fct_sales_fx_positive CHECK (
        fx_rate_to_cny IS NULL OR fx_rate_to_cny > 0
    ),
    CONSTRAINT ck_fct_sales_net_cny_nonnegative CHECK (
        net_sales_amount_cny IS NULL OR net_sales_amount_cny >= 0
    ),
    CONSTRAINT ck_fct_sales_unit_cost_nonnegative CHECK (
        frozen_unit_cost_cny IS NULL OR frozen_unit_cost_cny >= 0
    ),
    CONSTRAINT ck_fct_sales_cost_nonnegative CHECK (
        sales_cost_amount_cny IS NULL OR sales_cost_amount_cny >= 0
    ),
    CONSTRAINT ck_fct_sales_completed_complete CHECK (
        order_status <> 'completed'
        OR (
            completion_date_key IS NOT NULL
            AND quantity IS NOT NULL
            AND net_sales_amount_transaction IS NOT NULL
            AND transaction_currency_key IS NOT NULL
            AND fx_rate_to_cny IS NOT NULL
            AND net_sales_amount_cny IS NOT NULL
            AND frozen_unit_cost_cny IS NOT NULL
            AND sales_cost_amount_cny IS NOT NULL
        )
    ),
    CONSTRAINT ck_fct_sales_source_system CHECK (btrim(source_system) <> '')
);

-- SCD Type 2（第二型缓慢变化维度）：同一业务键只能有一个当前版本。
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_customer_current
    ON mart_sales.dim_customer (customer_id)
    WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_product_current
    ON mart_sales.dim_product (product_id)
    WHERE is_current;

-- 事实表 V1 明确查询路径索引；不引入分区或推测性索引。
CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_completion_date
    ON mart_sales.fct_sales_order_line (completion_date_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_customer
    ON mart_sales.fct_sales_order_line (customer_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_product
    ON mart_sales.fct_sales_order_line (product_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_sales_region
    ON mart_sales.fct_sales_order_line (sales_region_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_status
    ON mart_sales.fct_sales_order_line (order_status);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_completion_status
    ON mart_sales.fct_sales_order_line (completion_date_key, order_status);

-- Keep database comments as the source for Metadata Export descriptions.
COMMENT ON TABLE mart_sales.dim_currency IS '交易币种及其名称、币种标识信息。';
COMMENT ON TABLE mart_sales.dim_customer IS '客户业务主体及其属性历史版本数据。';
COMMENT ON TABLE mart_sales.dim_date IS '按自然日记录的日期及其年、季度、月、日属性。';
COMMENT ON TABLE mart_sales.dim_product IS '产品业务对象及其产品线、产品类别、技术路线和属性历史版本数据。';
COMMENT ON TABLE mart_sales.dim_sales_region IS '销售区域的编码和名称数据。';
COMMENT ON TABLE mart_sales.fct_exchange_rate_daily IS '按日期和交易币种记录的人民币汇率数据。';
COMMENT ON TABLE mart_sales.fct_sales_order_line IS '销售订单明细粒度的交易事实数据，包含订单、客户、产品、区域、时间、状态、数量和金额字段。';

COMMENT ON COLUMN mart_sales.dim_currency.currency_key IS '币种记录的代理键。';
COMMENT ON COLUMN mart_sales.dim_currency.currency_code IS '交易币种的三字母代码。';
COMMENT ON COLUMN mart_sales.dim_currency.currency_name IS '交易币种名称。';
COMMENT ON COLUMN mart_sales.dim_currency.is_analysis_currency IS '标识该币种是否被标记为分析币种。';

COMMENT ON COLUMN mart_sales.dim_customer.customer_key IS '客户属性版本记录的代理键。';
COMMENT ON COLUMN mart_sales.dim_customer.customer_id IS '客户业务主体的稳定标识。';
COMMENT ON COLUMN mart_sales.dim_customer.customer_name IS '客户业务主体名称。';
COMMENT ON COLUMN mart_sales.dim_customer.customer_type IS '客户业务主体的类型分类。';
COMMENT ON COLUMN mart_sales.dim_customer.industry IS '客户业务主体所属行业分类。';
COMMENT ON COLUMN mart_sales.dim_customer.country IS '客户业务主体所属国家。';
COMMENT ON COLUMN mart_sales.dim_customer.customer_region IS '客户业务主体所属区域。';
COMMENT ON COLUMN mart_sales.dim_customer.valid_from IS '客户属性版本的生效时间。';
COMMENT ON COLUMN mart_sales.dim_customer.valid_to IS '客户属性版本的失效时间，可为空。';
COMMENT ON COLUMN mart_sales.dim_customer.is_current IS '标识该客户属性版本是否为当前版本。';
COMMENT ON COLUMN mart_sales.dim_customer.source_system IS '客户记录的来源系统标识。';
COMMENT ON COLUMN mart_sales.dim_customer.source_updated_at IS '客户记录在来源系统中的更新时间。';
COMMENT ON COLUMN mart_sales.dim_customer.loaded_at IS '客户记录载入 mart_sales 的时间。';

COMMENT ON COLUMN mart_sales.dim_date.date_key IS '日期数字键，格式 YYYYMMDD。';
COMMENT ON COLUMN mart_sales.dim_date.full_date IS '自然日日期。';
COMMENT ON COLUMN mart_sales.dim_date.year IS '日期所属年份。';
COMMENT ON COLUMN mart_sales.dim_date.quarter IS '日期所属季度。';
COMMENT ON COLUMN mart_sales.dim_date.month IS '日期所属月份。';
COMMENT ON COLUMN mart_sales.dim_date.day IS '日期在所属月份中的日序号。';

COMMENT ON COLUMN mart_sales.dim_product.product_key IS '产品属性版本记录的代理键。';
COMMENT ON COLUMN mart_sales.dim_product.product_id IS '产品业务对象稳定标识。';
COMMENT ON COLUMN mart_sales.dim_product.product_name IS '产品业务对象名称。';
COMMENT ON COLUMN mart_sales.dim_product.product_line IS '产品所属产品线。';
COMMENT ON COLUMN mart_sales.dim_product.product_category IS '产品所属产品类别。';
COMMENT ON COLUMN mart_sales.dim_product.technology_route IS '产品采用的技术路线。';
COMMENT ON COLUMN mart_sales.dim_product.valid_from IS '产品属性版本生效时间。';
COMMENT ON COLUMN mart_sales.dim_product.valid_to IS '产品属性版本失效时间，可为空。';
COMMENT ON COLUMN mart_sales.dim_product.is_current IS '标识该产品属性版本是否为当前版本。';
COMMENT ON COLUMN mart_sales.dim_product.source_system IS '产品记录的来源系统标识。';
COMMENT ON COLUMN mart_sales.dim_product.source_updated_at IS '产品记录在来源系统中的更新时间。';
COMMENT ON COLUMN mart_sales.dim_product.loaded_at IS '产品记录载入 mart_sales 的时间。';

COMMENT ON COLUMN mart_sales.dim_sales_region.sales_region_key IS '销售区域记录的代理键。';
COMMENT ON COLUMN mart_sales.dim_sales_region.sales_region_code IS '销售区域编码。';
COMMENT ON COLUMN mart_sales.dim_sales_region.sales_region_name IS '销售区域名称。';

COMMENT ON COLUMN mart_sales.fct_exchange_rate_daily.rate_date_key IS '汇率记录对应日期键。';
COMMENT ON COLUMN mart_sales.fct_exchange_rate_daily.currency_key IS '对应币种键。';
COMMENT ON COLUMN mart_sales.fct_exchange_rate_daily.rate_to_cny IS '交易币种兑人民币汇率数值。';
COMMENT ON COLUMN mart_sales.fct_exchange_rate_daily.source_system IS '汇率记录的来源系统标识。';
COMMENT ON COLUMN mart_sales.fct_exchange_rate_daily.source_updated_at IS '汇率记录在来源系统中的更新时间。';
COMMENT ON COLUMN mart_sales.fct_exchange_rate_daily.loaded_at IS '汇率记录载入 mart_sales 的时间。';

COMMENT ON COLUMN mart_sales.fct_sales_order_line.sales_order_line_key IS '销售订单明细代理键。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.order_id IS '订单业务标识。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.order_no IS '订单业务编号。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.order_line_id IS '明细业务标识。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.order_line_no IS '订单内明细序号。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.customer_key IS '关联客户属性版本记录键。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.product_key IS '关联产品属性版本记录键。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.sales_region_key IS '关联销售区域记录键。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.transaction_currency_key IS '关联交易币种记录键。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.order_date_key IS '下单日期键。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.confirmation_date_key IS '确认日期键，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.completion_date_key IS '完成日期键，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.order_status IS '业务状态，包括 pending、confirmed、completed、cancelled。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.quantity IS '数量值。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.unit_price_transaction IS '交易币种下的单位价格。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.discount_amount_transaction IS '交易币种下的折扣金额。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.gross_sales_amount_transaction IS '交易币种下的折前销售金额。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.net_sales_amount_transaction IS '交易币种下的净销售金额，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.fx_rate_to_cny IS '对应交易币种兑人民币汇率，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.net_sales_amount_cny IS '按人民币记录的明细净销售金额，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.frozen_unit_cost_cny IS '按人民币记录的明细冻结单位成本，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.sales_cost_amount_cny IS '按人民币记录的明细销售成本金额，可为空。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.source_system IS '销售订单明细记录的来源系统标识。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.source_updated_at IS '销售订单明细记录在来源系统中的更新时间。';
COMMENT ON COLUMN mart_sales.fct_sales_order_line.loaded_at IS '销售订单明细记录载入 mart_sales 的时间。';
