-- Sales Mart V1（销售数据集市第一版）物理模型。
--
-- 边界：
-- 1. 只创建 mart_sales，不删除或修改 legacy public Schema（旧 public 模式）。
-- 2. 事实表一行对应一条 Sales Order Line（销售订单明细）。
-- 3. Completed（已完成）事实必须保存完成日期、冻结汇率、人民币销售额和冻结销售成本。
-- 4. Gross Profit / Gross Margin（毛利 / 毛利率）留在下游 Semantic Layer（语义层）派生。

CREATE SCHEMA IF NOT EXISTS mart_sales;

CREATE TABLE IF NOT EXISTS mart_sales.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    year SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    day SMALLINT NOT NULL,
    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date),
    CONSTRAINT ck_dim_date_parts CHECK (
        year = EXTRACT(YEAR FROM full_date)::SMALLINT
        AND quarter = EXTRACT(QUARTER FROM full_date)::SMALLINT
        AND month = EXTRACT(MONTH FROM full_date)::SMALLINT
        AND day = EXTRACT(DAY FROM full_date)::SMALLINT
    ),
    CONSTRAINT ck_dim_date_quarter CHECK (quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_dim_date_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_date_day CHECK (day BETWEEN 1 AND 31),
    CONSTRAINT ck_dim_date_key CHECK (
        date_key = (
            EXTRACT(YEAR FROM full_date)::INTEGER * 10000
            + EXTRACT(MONTH FROM full_date)::INTEGER * 100
            + EXTRACT(DAY FROM full_date)::INTEGER
        )
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_customer (
    customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    customer_name TEXT NOT NULL,
    customer_type TEXT NOT NULL,
    industry TEXT NOT NULL,
    country TEXT NOT NULL,
    customer_region TEXT NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_customer_business_version UNIQUE (customer_id, valid_from),
    CONSTRAINT ck_dim_customer_source_system CHECK (btrim(source_system) <> ''),
    CONSTRAINT ck_dim_customer_version_bounds CHECK (
        valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT ck_dim_customer_current_flag CHECK (
        (is_current AND valid_to IS NULL)
        OR (NOT is_current AND valid_to IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_product (
    product_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    product_name TEXT NOT NULL,
    product_line TEXT NOT NULL,
    product_category TEXT NOT NULL,
    technology_route TEXT NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_product_business_version UNIQUE (product_id, valid_from),
    CONSTRAINT ck_dim_product_source_system CHECK (btrim(source_system) <> ''),
    CONSTRAINT ck_dim_product_version_bounds CHECK (
        valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT ck_dim_product_current_flag CHECK (
        (is_current AND valid_to IS NULL)
        OR (NOT is_current AND valid_to IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_sales_region (
    sales_region_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_region_code VARCHAR(50) NOT NULL,
    sales_region_name TEXT NOT NULL,
    CONSTRAINT uq_dim_sales_region_code UNIQUE (sales_region_code),
    CONSTRAINT ck_dim_sales_region_code CHECK (btrim(sales_region_code) <> '')
);

CREATE TABLE IF NOT EXISTS mart_sales.dim_currency (
    currency_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3) NOT NULL,
    currency_name TEXT NOT NULL,
    is_analysis_currency BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_dim_currency_code UNIQUE (currency_code),
    CONSTRAINT ck_dim_currency_code CHECK (
        char_length(currency_code) = 3
        AND currency_code = btrim(upper(currency_code))
    ),
    CONSTRAINT ck_dim_currency_analysis_code CHECK (
        is_analysis_currency = (currency_code = 'CNY')
    )
);

CREATE TABLE IF NOT EXISTS mart_sales.fct_exchange_rate_daily (
    rate_date_key INTEGER NOT NULL,
    currency_key BIGINT NOT NULL,
    rate_to_cny NUMERIC(20, 8) NOT NULL,
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_fct_exchange_rate_daily PRIMARY KEY (rate_date_key, currency_key),
    CONSTRAINT fk_fct_exchange_rate_date
        FOREIGN KEY (rate_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT fk_fct_exchange_rate_currency
        FOREIGN KEY (currency_key) REFERENCES mart_sales.dim_currency (currency_key),
    CONSTRAINT ck_fct_exchange_rate_positive CHECK (rate_to_cny > 0),
    CONSTRAINT ck_fct_exchange_rate_source_system CHECK (btrim(source_system) <> '')
);

CREATE TABLE IF NOT EXISTS mart_sales.fct_sales_order_line (
    sales_order_line_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_no VARCHAR(100) NOT NULL,
    order_line_id BIGINT NOT NULL,
    order_line_no INTEGER NOT NULL,
    customer_key BIGINT NOT NULL,
    product_key BIGINT NOT NULL,
    sales_region_key BIGINT NOT NULL,
    transaction_currency_key BIGINT NOT NULL,
    order_date_key INTEGER NOT NULL,
    confirmation_date_key INTEGER,
    completion_date_key INTEGER,
    order_status VARCHAR(20) NOT NULL,
    quantity NUMERIC(20, 6) NOT NULL,
    unit_price_transaction NUMERIC(20, 6) NOT NULL,
    discount_amount_transaction NUMERIC(20, 6) NOT NULL DEFAULT 0,
    gross_sales_amount_transaction NUMERIC(20, 6) NOT NULL,
    net_sales_amount_transaction NUMERIC(20, 6),
    fx_rate_to_cny NUMERIC(20, 8),
    net_sales_amount_cny NUMERIC(20, 6),
    frozen_unit_cost_cny NUMERIC(20, 6),
    sales_cost_amount_cny NUMERIC(20, 6),
    source_system TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fct_sales_order_line_id UNIQUE (order_line_id),
    CONSTRAINT uq_fct_sales_order_line_order_line_no UNIQUE (order_id, order_line_no),
    CONSTRAINT fk_fct_sales_customer
        FOREIGN KEY (customer_key) REFERENCES mart_sales.dim_customer (customer_key),
    CONSTRAINT fk_fct_sales_product
        FOREIGN KEY (product_key) REFERENCES mart_sales.dim_product (product_key),
    CONSTRAINT fk_fct_sales_region
        FOREIGN KEY (sales_region_key) REFERENCES mart_sales.dim_sales_region (sales_region_key),
    CONSTRAINT fk_fct_sales_currency
        FOREIGN KEY (transaction_currency_key) REFERENCES mart_sales.dim_currency (currency_key),
    CONSTRAINT fk_fct_sales_order_date
        FOREIGN KEY (order_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT fk_fct_sales_confirmation_date
        FOREIGN KEY (confirmation_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT fk_fct_sales_completion_date
        FOREIGN KEY (completion_date_key) REFERENCES mart_sales.dim_date (date_key),
    CONSTRAINT ck_fct_sales_order_line_no CHECK (order_line_no > 0),
    CONSTRAINT ck_fct_sales_order_no CHECK (btrim(order_no) <> ''),
    CONSTRAINT ck_fct_sales_status CHECK (
        order_status IN ('pending', 'confirmed', 'completed', 'cancelled')
    ),
    CONSTRAINT ck_fct_sales_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_fct_sales_unit_price_nonnegative CHECK (unit_price_transaction >= 0),
    CONSTRAINT ck_fct_sales_discount_nonnegative CHECK (discount_amount_transaction >= 0),
    CONSTRAINT ck_fct_sales_gross_nonnegative CHECK (gross_sales_amount_transaction >= 0),
    CONSTRAINT ck_fct_sales_net_transaction_nonnegative CHECK (
        net_sales_amount_transaction IS NULL OR net_sales_amount_transaction >= 0
    ),
    CONSTRAINT ck_fct_sales_fx_positive CHECK (
        fx_rate_to_cny IS NULL OR fx_rate_to_cny > 0
    ),
    CONSTRAINT ck_fct_sales_net_cny_nonnegative CHECK (
        net_sales_amount_cny IS NULL OR net_sales_amount_cny >= 0
    ),
    CONSTRAINT ck_fct_sales_unit_cost_nonnegative CHECK (
        frozen_unit_cost_cny IS NULL OR frozen_unit_cost_cny >= 0
    ),
    CONSTRAINT ck_fct_sales_cost_nonnegative CHECK (
        sales_cost_amount_cny IS NULL OR sales_cost_amount_cny >= 0
    ),
    CONSTRAINT ck_fct_sales_completed_complete CHECK (
        order_status <> 'completed'
        OR (
            completion_date_key IS NOT NULL
            AND quantity IS NOT NULL
            AND net_sales_amount_transaction IS NOT NULL
            AND transaction_currency_key IS NOT NULL
            AND fx_rate_to_cny IS NOT NULL
            AND net_sales_amount_cny IS NOT NULL
            AND frozen_unit_cost_cny IS NOT NULL
            AND sales_cost_amount_cny IS NOT NULL
        )
    ),
    CONSTRAINT ck_fct_sales_source_system CHECK (btrim(source_system) <> '')
);

-- SCD Type 2（第二型缓慢变化维度）：同一业务键只能有一个当前版本。
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_customer_current
    ON mart_sales.dim_customer (customer_id)
    WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_product_current
    ON mart_sales.dim_product (product_id)
    WHERE is_current;

-- 事实表 V1 明确查询路径索引；不引入分区或推测性索引。
CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_completion_date
    ON mart_sales.fct_sales_order_line (completion_date_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_customer
    ON mart_sales.fct_sales_order_line (customer_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_product
    ON mart_sales.fct_sales_order_line (product_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_sales_region
    ON mart_sales.fct_sales_order_line (sales_region_key);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_status
    ON mart_sales.fct_sales_order_line (order_status);

CREATE INDEX IF NOT EXISTS idx_fct_sales_order_line_completion_status
    ON mart_sales.fct_sales_order_line (completion_date_key, order_status);
