kind: project

entrypoint: main.tsp

warn-as-error: true

emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/generated"
    output-file: "openapi.{version}.yaml"
    file-type: "yaml"
    openapi-versions:
      - "3.2.0"
    omit-unreachable-types: true